# Generated by Django 5.0.4 on 2024-04-18 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_medicament', models.CharField(max_length=100)),
                ('description', models.TextField(default='description to medicament')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name_medicine',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_photo',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='medication_photo',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Medical_consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.medical_consultation_history')),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.treatment')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='medicament',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.medicament'),
        ),
    ]
